on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"

name: Publish to DockerHub

jobs:
  dockerhub:
    name: Build and Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPOSITORY }}
          tags: latest
          tag_with_sha: true
